from MSRP import MSRP
from SICK import SICK
from SNLI import SNLI
from SST import SST
from PDTB2 import PDTB2
from bAbI import BABI
from CBT import CBT
from MSCOCO import MSCOCO
from PascalSentences import PascalSentences
from BllipWithoutParseTrees import BllipWithoutParseTrees
